import React from 'react';
import { StyleSheet, Text, View, ScrollView, TouchableOpacity, Platform } from 'react-native';
import { MaterialCommunityIcons } from '@expo/vector-icons';
import { useRouter } from 'expo-router';
import { useTheme } from '../context/ThemeContext';
import { theme } from '../constants/theme';
import AppHeader from '../components/AppHeader';


interface TermsSection {
  title: string;
  body: string;
}

const sections: TermsSection[] = [
  {
    title: 'Content Generated by AI',
    body: 'This app uses artificial intelligence to generate responses. All content marked as "Generated by AI" is produced by machine learning models and should be verified for accuracy.\n\nAI-generated content may contain errors. Always verify important information.',
  },
  {
    title: 'Important Disclaimers',
    body: '• AI-generated content may contain errors or inaccuracies\n• Responses are based on training data and may not reflect current events\n• Do not rely on AI content for medical, legal, or financial advice\n• Always verify important information from authoritative sources',
  },
  {
    title: 'Safety & Content Policy',
    body: '• AI models are designed to refuse harmful content generation\n• Content filters may not catch all potentially harmful output\n• Users are responsible for appropriate use of AI features',
  },
];

const ContentTermsScreen = () => {
  const router = useRouter();
  const { theme: currentTheme } = useTheme();
  const themeColors = theme[currentTheme];

  const renderSection = (section: TermsSection, index: number) => (
    <View
      key={index}
      style={[
        styles.sectionItem,
        { borderBottomColor: themeColors.borderColor },
      ]}
    >
      <Text style={[styles.sectionTitle, { color: themeColors.text }]}>
        {section.title}
      </Text>
      <Text style={[styles.sectionBody, { color: themeColors.secondaryText }]}>
        {section.body}
      </Text>
    </View>
  );

  return (
    <View style={[styles.container, { backgroundColor: themeColors.background }]}>
      <AppHeader
        title="AI Content Terms"
        leftComponent={
          <TouchableOpacity
            style={styles.backButton}
            onPress={() => router.back()}
            hitSlop={{ top: 10, bottom: 10, left: 10, right: 10 }}
          >
            <MaterialCommunityIcons name="arrow-left" size={24} color={Platform.OS === 'ios' && currentTheme === 'light' ? themeColors.primary : themeColors.headerText} />
          </TouchableOpacity>
        }
        rightButtons={[]}
      />

      <ScrollView
        style={styles.scrollView}
        contentContainerStyle={styles.contentContainer}
        showsVerticalScrollIndicator={false}
      >
        <View style={styles.sectionsContainer}>
          {sections.map((section, index) => renderSection(section, index))}
        </View>
      </ScrollView>
    </View>
  );
};

const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  backButton: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: 'rgba(255, 255, 255, 0.15)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  scrollView: {
    flex: 1,
  },
  contentContainer: {
    padding: 16,
    paddingBottom: 32,
  },
  sectionsContainer: {
    gap: 16,
  },
  sectionItem: {
    borderRadius: 12,
    padding: 16,
    borderBottomWidth: 1,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: '600',
    marginBottom: 8,
  },
  sectionBody: {
    fontSize: 14,
    lineHeight: 22,
  },
});

export default ContentTermsScreen;
